---
name: YAML Syntax Check and Send a request to CloudOrchestrate

on:
  push:
    branches:
      - dev
      - master
    paths:
      - '**.yaml'
      - '**.yml'
      - 'script.py'
  pull_request:
    branches:
      - dev
      - master
    paths:
      - '**.yaml'
      - '**.yml'
      - 'script.py'

jobs:
  validate-and-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install yamllint
          python -m pip install -r requirements.txt

      - name: Lint YAML files
        run: |
          yamllint .

      - name: Run Python script
        run: |
          python send_payload.py
